### ISSUE TITLE
Installing the QIIME 2 "system"

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#101]
This is just a thread to track discussion for creating installers/distributions for QIIME 2/plugins/interfaces.

It looks like Anaconda has open-sourced their installer:
https://github.com/conda/constructor

So that may be worth looking into, though I have no idea how it would interact with something like an electron installer.

**Comment by jairideout** [comment]
This is pretty old -- closing since we've defined distributions (just Core for now) and have exported environment files for easy installation. There's also a packaging/installer issue for q2studio here: https://github.com/qiime2/q2studio/issues/103

Please reopen if I misinterpreted this issue's intent.
