### ISSUE TITLE
Plugin should have an associated Citation object 

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#113]
This would be in addition to (or replacing) `citation_text`, and could contain things like DOI, BibTex formatted citation, and action-specific citations.

**Comment by josenavas** [comment]
I really like the idea of adding a way for the citations. I'm unsure which are your goals with this, but in Qiita we have a similar approach, and in order to avoid multiple problems such that duplication of effort or sync problems, we decided to just store the DOI, as with that information the user can download the bibtex formatted citation, given that the official pages already have mechanisms to provide this information, and other information. Just wanted to throw this in there, since it may simplify the design of this part.

**Comment by mdeleeuw** [comment]
Please note currently reported citation and help URLs are not working, since all plugins are under qiime2 and not qiime2-plugins on Github

    Usage: qiime feature-table [OPTIONS] COMMAND [ARGS]...
    Plugin website: https://github.com/qiime2-plugins/q2-feature-table
    Getting user support: No user support information available. See plugin website: 
    https://github.com/qiime2-plugins/q2-feature-table
    Citing this plugin: No citation available. Cite plugin website:
    https://github.com/qiime2-plugins/q2-feature-table

**Comment by jairideout** [comment]
@mdeleeuw this has been fixed upstream and the fix will be available in the next release. Note that the incorrect URL only applies to the `q2-feature-table` plugin.
