### ISSUE TITLE
Prevent duplicate directory format registrations for a semantic type

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#134]
**Current Behavior**
`register_semantic_type_to_format` doesn't check for duplicate registrations.

**Proposed Behavior**
Maybe drop the list and use a dict here 

**References**
(this could possibly make the work in https://github.com/qiime2/qiime2/pull/133 more efficient).

**Comment by ebolyen** [comment]
A `dict` won't quite work because we would need to look up the format for 
`SomeType % Properties("Foo")` (a subtyping question) and we can't register all possible semantic types. It may be possible to strip the predicate, but then we would lose `SomeType[A | B | C]`, but maybe that is ok. 

Also you would have to strip *all* predicates. `Foo[A % Properties("Bar")]` is a subtype of `Foo[A]`

**Comment by Oddant1** [comment]
It looks like we do now ensure that a given semantic type is only registered once
