### ISSUE TITLE
could model.File support a regex path?

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#148]
**Improvement Description**
It would be nice to support more than one acceptable path name for `model.File` (regex). See q2-demux for an example ([these two directory formats specifically](https://github.com/qiime2/q2-demux/pull/1/files#diff-d9d326294f2b2104eccbfe4232f5b4c3R5)). In that example, we're wanting to allow users to import two files, each with two filename options.

**Questions**
Or is it better to use a `model.FileCollection` of size 1 with a regex? If so, how do we validate the number of regex matches?

**References**
[these two directory formats specifically](https://github.com/qiime2/q2-demux/pull/1/files#diff-d9d326294f2b2104eccbfe4232f5b4c3R5)

**Comment by ebolyen** [comment]
I think we can re-frame "number of regex matches" in terms of mutual exclusion which would solve the related problem for `SingleLanePerSampleSingleEndFastqDirFmt`, where we expect all of the matched files to share some property of the regex (collectively forward xor reversed)

Basically we already need a way to manage mutually exclusive matches in the context of the entire collection (1 or otherwise). Permitting `model.File` to have a regex is interesting as it forces mutual exclusion by virtue of `n=1` (it also makes intuitive sense so I would support adding this), but I also suspect that it is better to think about this in the context `xor` instead of restricting size on `FileCollection`.

Incidentally, I am pretty sure you could just hand `model.File` a regex and there's a good chance it will work outright.

**Comment by Oddant1** [comment]
I think we do this now don't we?
