### ISSUE TITLE
FastTree build recommended for install does not run on RHEL6

### ISSUE THREAD

**Issue by wasade** [qiime2/qiime2#191]
Specifically:

`conda install -c biocore fasttree`

...as referenced in the tutorial. I'd link to the exact line but I'm not seeing where the documentation is. (The "fork me" link on the tutorial pointed to this repository). Suggested fix is to install from bioconda:

`conda install -c bioconda fasttree`

**Comment by jairideout** [comment]
@ebolyen, I remember you guys had a reason for using FastTree in `biocore` instead of `bioconda` channel (it came up while we were in Iceland for 2.0.5). Do you know if it's safe to use `bioconda` instead?

**Comment by ebolyen** [comment]
One of those channels was only missing the build for Mac OSX. But I think that was `mafft`...

**Comment by jairideout** [comment]
Thanks @ebolyen. `mafft` is being obtained from `bioconda` (they have builds for Linux and Mac).

`fasttree` is only available for Linux in `bioconda`, so we can't use that channel until a Mac build is available. @wasade, I'll keep this issue open so that we can update the install docs when `fasttree` is obtainable from `bioconda`.

**Comment by gregcaporaso** [comment]
bioconda now has macOS binaries for FastTree, so we can make this change. Closing in favor of https://github.com/qiime2/docs/issues/119.
