### ISSUE TITLE
Autoimport for non-Artifacts

### ISSUE THREAD

**Issue by BenKaehler** [qiime2/qiime2#204]
**Improvement Description**
Perhaps when a user attempts to use an object or file that is not an Artifact as an input to a QIIME method, but that would be appropriate for import into an Artifact that is of the type that the method expects as that input, QIIME could automatically import it into an appropriate Artifact and continue.

**Comments**
Obviously there are some details that we would need to think through, but it might increase usability and reduce a whole bunch of "import import import process" steps.

**Comment by ebolyen** [comment]
:+1: we should have mostly enough information to make this work (we know the context in which it's being used, so we have the semantic type already) and combined with some improved format detection #201 this would be a really convenient feature.

**Comment by jairideout** [comment]
I like this idea as a usability enhancement, but where would the artifacts be saved that are automatically imported? For provenance/reproducibility it'd be important to create each imported artifact and provide them to the user (to avoid ephemeral artifacts).

**Comment by ebolyen** [comment]
@jairideout I don't see why an ephemeral artifact would really matter. The import would be recorded in provenance with the appropriate md5sums (if file(s)). So it doesn't seem like a different situation from importing, running the method, and then deleting the original imported artifacts, provenance still captures the relevant bits. The only real downside is that if you wanted to do more things with the same data, you'd end up with a bunch of UUIDs which referenced the same data, but that's already possible situation.

**Comment by BenKaehler** [comment]
Thanks @jairideout and @ebolyen, this is not much different to doing it using the Python API, where one can easily import into an Artifact in memory, use it, and then the Artifact is lost when the script finishes.

If it is a concern then we could require that the `output-dir` is specified if the user wants to invoke auto-import.

**Comment by jairideout** [comment]
> The only real downside is that if you wanted to do more things with the same data, you'd end up with a bunch of UUIDs which referenced the same data, but that's already possible situation.

That's what I'm concerned about -- we'd lose the ancestral relationship between artifacts in provenance.

> Thanks @jairideout and @ebolyen, this is not much different to doing it using the Python API, where one can easily import into an Artifact in memory, use it, and then the Artifact is lost when the script finishes.
>
> If it is a concern then we could require that the output-dir is specified if the user wants to invoke auto-import.

That's true, and perhaps making this an "opt-in" feature is enough to mitigate the above issue.

Another potential pitfall: If we automatically import data, the user isn't necessarily aware of the semantic type associated with the raw data. Even if the raw data matches a transformer so that it can be used as input to a method, the semantics may not make sense. Effectively this allows users to bypass the semantic type system, and we wouldn't want to encourage that. (We have talked about a similar feature in the past, where users could override semantic type mismatches.)

Maybe forcing users to opt-in is enough to address these two concerns. I want to note that the "import import import process" should become less of an issue once QIIME 2 is closer to being feature-complete. Users won't need to export and re-import data as frequently because they'll be performing more/all analyses with QIIME 2.

**Comment by ebolyen** [comment]
> That's what I'm concerned about -- we'd lose the ancestral relationship between artifacts in provenance.

Nothing is lost though, the md5sums are already taken, or it is otherwise an object and completely ephemeral from QIIME's point of view anyways. I'm not sure I'm understanding your point. Are you considering the potential for not being able to relate pseudo-sibling artifacts as being derived from the same raw source? I think that is reasonable, but it's kind of an issue anyways, and if it was sufficiently important, once again the real solution is to check the md5sums instead of the UUID (deep vs referential equality). If the import didn't involve md5sums, then you already have a very large hole in your provenance, that nothing we do can really solve.

> Another potential pitfall: If we automatically import data, the user isn't necessarily aware of the semantic type associated with the raw data. Even if the raw data matches a transformer so that it can be used as input to a method, the semantics may not make sense. Effectively this allows users to bypass the semantic type system, and we wouldn't want to encourage that. (We have talked about a similar feature in the past, where users could override semantic type mismatches.)

This is a different situation I think because the user is explicitly using the data in the context of a semantic type (as an argument to a typed parameter), it's effectively an import, just virtual. An import has the same pitfalls anyways, if you don't understand the semantics of your data, there's nothing to stop you from importing it as the wrong type, and then using it.

I think the only downside is the lack of referential equality if you do repeated operations, but as @BenKaehler pointed out this isn't much different from just using the Python API in a typical way.

I'd be in favor of discussing this further in person next week(-ish).
