### ISSUE TITLE
Exception in Archiver.__del__

### ISSUE THREAD

**Issue by wasade** [qiime2/qiime2#223]
The code to produce this is below -- just needs two tree artifacts. I do not think the calls to things like `shear` are pertinent, but the script was small where this was first observed so just pasting it anyway. The exception appears to be stochastic.

```bash
Exception ignored in: <bound method Archiver.__del__ of <qiime2.core.archive.archiver.Archiver object at 0x7f929dc5ff28>>
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/q2-2017.2/lib/python3.5/site-packages/qiime2-2017.2.0-py3.5.egg/qiime2/core/archive/archiver.py", line 347, in __del__
  File "/home/mcdonadt/miniconda3/envs/q2-2017.2/lib/python3.5/shutil.py", line 473, in rmtree
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Archiver.__del__ of <qiime2.core.archive.archiver.Archiver object at 0x7f929dc7bf98>>
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/q2-2017.2/lib/python3.5/site-packages/qiime2-2017.2.0-py3.5.egg/qiime2/core/archive/archiver.py", line 347, in __del__
  File "/home/mcdonadt/miniconda3/envs/q2-2017.2/lib/python3.5/shutil.py", line 473, in rmtree
TypeError: 'NoneType' object is not callable
```

```python
import qiime2
import skbio
import sys

ar_a = qiime2.Artifact.load(sys.argv[1])
ar_b = qiime2.Artifact.load(sys.argv[2])

t_a = ar_a.view(skbio.TreeNode)
t_b = ar_b.view(skbio.TreeNode)

ids_a = {n.name for n in t_a.tips()}
ids_b = {n.name for n in t_b.tips()}

print("Total ids: %d" % len(ids_a | ids_b))
print("Total ids A: %d" % len(ids_a))
print("Total ids B: %d" % len(ids_b))
print("Total unique: %d" % len(ids_a.symmetric_difference(ids_b)))

overlap = ids_a & ids_b
t_a_o = t_a.shear(overlap)
t_b_o = t_b.shear(overlap)

print("RFD: %f" % t_a_o.compare_rfd(t_b_o, True))
print("tip-tip comparison: %f" % t_a_o.compare_tip_distances(t_b_o))
```

**Comment by ebolyen** [comment]
I think we may have figured out why this happens. When the artifact goes out of scope as the program is exiting, the environment isn't stable and stdlib functions are being `None`-ed out. If the artifact was inside of a scoped block or otherwise deleted with `del` before the program exits, the destructor seems to run as expected. (Although this isn't a guarantee, since the GC is allowed to do "anything" in principle).

We will need to adapt this destructor to work more like the `NamedTemporaryFile` objects, which have to do some [special hackery](https://github.com/python/cpython/blob/3.6/Lib/tempfile.py#L416) to make these objects clean up correctly.

**Comment by ebolyen** [comment]
More specifically we just need to use [weakref.finalize](https://docs.python.org/3/library/weakref.html#weakref.finalize) it looks like. It is always called before interpreter shutdown.
