### ISSUE TITLE
support optional artifacts

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#235]

**Comment by BenKaehler** [comment]
It may be useful for the `feature-classifier` classifier training methods to accept prior class weights at some point. The weights will be a list of thousands of (taxonomy, float) pairs. It is unlikely that users will be happy with this input being a requirement, at least initially, so it would be good if it were optional. Further, duplicating all of the classifier training methods so that one takes weights and the other doesn't is not an awesome idea.

It should be noted that the importance of this issue will be modified by the results of the tests that @nbokulich and I are currently performing.

**Comment by antgonza** [comment]
It will also be useful for `qiime diversity core-metrics` so we can have an optional tree and have `non-phylogenetic` parameter
