### ISSUE TITLE
avoid duplicating files when importing the raw sequence files

### ISSUE THREAD

**Issue by RNAer** [qiime2/qiime2#260]
**Current Behavior**
in qiime2-2017.4, to start the analysis, I need to import the raw sequence to qiime artifact. This duplicates the raw files. In lots of cases, the multiplexed raw files are big and contain reads from multiple studies. Thus it really takes huge space to duplicate the whole files from a HiSeq lane, for example.

**Questions**
Would it be better to just contain the file path/url/ect to the raw sequences in the artifact?

**Comment by jairideout** [comment]
QIIME 2 artifacts are intended to be self-contained / self-descriptive so that they can be moved around (e.g. onto different systems) and archived for later use. Encoding a file path would make the artifact bound to a specific file system, and using a URL wouldn't guarantee that the external data is accessible in the future.

We're aware of this limitation but decided it's probably not a deal breaker since HDD space is cheap and continually expanding in capacity.

I'm interested in potentially supporting this feature though -- perhaps the QIIME 2 artifact could indicate that it isn't "archival-quality" if it links to external resources.

@ebolyen @thermokarst @gregcaporaso what are your thoughts on this?

**Comment by ebolyen** [comment]
My interpretation is that an "implicit" import would work, where we still generate an archive and do the md5sums of everything, we just don't bother creating a zip file out of it. We discussed this a bit in #204

**Comment by jairideout** [comment]
That would solve the size issue, but then you wouldn't have complete provenance -- the data would always be "raw" and a *new* implicit artifact with uninteresting provenance would be created each time you use the raw data. This would make it hard to link downstream results back to the artifact they were derived from.

What do you think about my idea above re: .qza files that aren't "archival quality"? I think it addresses the size and provenance issues.

**Comment by gregcaporaso** [comment]
I like the idea of the _non archival quality_ artifacts for this.

**Comment by jairideout** [comment]
@ebolyen @thermokarst @gregcaporaso and I met yesterday to discuss this issue and reached consensus on "non archival quality" artifacts, which will solve @RNAer's size issue and promote better use of provenance over implicit artifacts.

#204 can stay open and needs additional discussion on whether we'll support implicit artifacts. The ideas in #204 are orthogonal and don't conflict with the feature discussed in this issue.

**Comment by RNAer** [comment]
Thanks! It will be exciting to see this happen.

**Comment by Oddant1** [comment]
This is kinda solved by the cache
