### ISSUE TITLE
QIIME 2 VirtualBox Images 2017.5 corrupt

### ISSUE THREAD

**Issue by gisleDK** [qiime2/qiime2#284]
Attempted several different ways to download the VirtualBox Image v2017.5 from
https://data.qiime2.org/distro/core/2017.5 but always end up with a corrupted zipfile. Please advice
warning [2017.5.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
replace QIIME 2 Core - 2017.5 (1495755264)/QIIME 2 Core - 2017.5 (1495755264)-disk001.vmdk? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: QIIME 2 Core - 2017.5 (1495755264)/QIIME 2 Core - 2017.5 (1495755264)-disk001.vmdk
  error:  invalid compressed data to inflate
file #3:  bad zipfile offset (local header sig):  476126507
  (attempting to re-compensate)
replace QIIME 2 Core - 2017.5 (1495755264)/QIIME 2 Core - 2017.5 (1495755264).ovf? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: QIIME 2 Core - 2017.5 (1495755264)/QIIME 2 Core - 2017.5 (1495755264).ovf

**Comment by thermokarst** [comment]
Hi @gisleDK: the zip file hosted at https://data.qiime2.org/distro/core/2017.5 appears to be okay --- I just downloaded and installed the VM as a quick check and didn't encounter the errors you showed above. Perhaps your internet connection has been interrupted in some way, corrupting the zip file? Maybe your ZIP tool is modifying the zip file somehow?

The correct md5sum of the 2017.5 zip file is `b36d2b44a720d7c231ce6261fc93f53d`. You can check that by running

```bash
md5 /path/to/downloaded/qiime2.zip
```

Unfortunately there isn't anything we can do to help with that, since the hosted file has been confirmed to be valid, and transfers from the file server have also been confirmed to work. Perhaps you could try on a different internet connection? Good luck!

PS - You can reach out to us at https://forum.qiime2.org for additional help --- that is where we field support and help questions. If bugs are identified during support, we will make sure the issues are filed in the appropriate github project. Also, you don't need to sign up for a new account there, you can use your github account to log in (or google account, if you prefer).

**Comment by gisleDK** [comment]
Thanks for checking. I will give it another go.
