### ISSUE TITLE
Metadata internals: everything should be `str`type

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#298]

**Comment by ElDeveloper** [comment]
I usually opt for this approach (keeping all my data as a string), and only cast data as I specifically request that a column act either as a number, date, etc.

**Comment by antgonza** [comment]
I agree, that's the easiest/simplest and that will not make you crazy. If interested, we can discuss over beers all the fun we had with this in Qiita!

**Comment by jairideout** [comment]
Fixed in #359. Once a `Metadata` object exists in memory (either loaded from a metadata file, or constructed from a `pd.DataFrame`), each column has an appropriate `dtype` associated with it: `numeric` columns store `float`, and `categorical` columns store `str`. Missing data (represented by `np.nan`) can exist in either column type.
