### ISSUE TITLE
MIENS compliance on sample IDs 

### ISSUE THREAD

**Issue by wasade** [qiime2/qiime2#334]
See the discussion on the forum [here](https://forum.qiime2.org/t/deblur-problem-duplicate-sample-ids-error/1213/10). The sample IDs allowed by QIIME2 are not currently assured to be MIENS complaint. This was discovered in biocore/deblur#157, subsequently qiime2/q2-deblur#48 where the check (and subsequent exception) was thrown. This is a MIENS compliance issue as noted in QIIME1 (e.g., [check_id_map.py](https://github.com/biocore/qiime/blob/master/qiime/check_id_map.py#L918-L919)).

**Comment by jairideout** [comment]
We intentionally aren't forcing MIENS-compliant sample IDs (this is part of relaxing the QIIME metadata format requirements). See [my followup](https://forum.qiime2.org/t/deblur-problem-duplicate-sample-ids-error/1213/11?u=jairideout) on that forum post for details and examples.

Additionally, there's a good amount of QIIME 2 `.qza` files containing IDs that violate MIENS standards, so it would be tough on our users if we backtrack at this point (their data would be unusable with QIIME 2, something we've worked hard to avoid).

**Comment by ebolyen** [comment]
Is there a resource to learn more about MIENS? I'm pretty unfamiliar with it.

**Comment by wasade** [comment]
@ebolyen http://precedings.nature.com/documents/5252/version/2

@jairideout, that is not a good reason to disregard an established community standard that QIIME used to abide by. The potential for silent bugs is high which makes the cost of user pain (of alpha software) worth it.

**Comment by thermokarst** [comment]
@wasade, thanks for the reference link, I was also having a hard time finding something.

Sorry for any confusion here, but it looks like we might not all be on the same page --- what @jairideout is proposing isn't to disregard this established community standard, I think he is advocating for a per-plugin/per-action approach. The reasoning is that while any one standard might work well for some tools (e.g. `deblur`), there is a (sometimes pretty likely) chance that those standards aren't applicable for another tool (e.g. `PHYLIP`). This per-plugin / per-action approach was actually why I had opened https://github.com/qiime2/q2-deblur/issues/48 - because we have already generally been approaching these problems on a per-plugin / per-action basis. Personally I don't think that the per-plugin / per-action approach is incompatible with supporting established community standards, I just think it might need to happen at a different tier (instead of framework-wide). I might still be misunderstanding your view (apologies if I am!), and if that is the case, maybe we can chat about it on an upcoming weekly dev call. Thanks!

**Comment by jairideout** [comment]
> which makes the cost of user pain (of alpha software) worth it.

@wasade, QIIME 2 is no longer in alpha status, so we can't really backtrack on this. We've taken great pains to support existing user data in a backwards-compatible way -- if we hadn't, we would have been able to focus much more of our efforts on project implementation, but we've been prioritizing user-experience (which is paying off in practice).

> The potential for silent bugs is high

Please read my forum post. I provided a logical argument for why adopting MIENS-compliant sample IDs **does not** solve the problem you brought up.

> that is not a good reason to disregard an established community standard that QIIME used to abide by. 

There are many things that have changed between QIIME 1 and 2. In QIIME 2 we strive to be backwards-compatible with QIIME 1, and that includes being backwards-compatible with MIENS-compliant sample IDs. If a plugin/method/tool only works with MIENS-compliant IDs, the plugin developer can remap IDs as necessary. I think your statement about disregarding established community standards is unfair.

**Comment by wasade** [comment]
I read the post before I responded. We've always deferred identifier remapping to as close to the tool as necessary (e.g., the app controllers); the plugins are a new take on an old problem. The sample information is not a plugin though. QIIME either is or is not MIENS complaint and I really don't feel that there is a grey area there. If it is not MIENS compliant, then it disregards a widely accepted community standard and we're just scratching the surface of interoperability issues that this introduces.

**Comment by rob-knight** [comment]
Note that MIENS was superseded by MIMARKS, reference pub here:

https://www.ncbi.nlm.nih.gov/m/pubmed/21552244/

And curr info on GSC site. A lot of funding agencies care that QIIME is GSC standards compliant so I urge you to reconsider this in the strongest possible terms.

On Sep 13, 2017, at 8:37 PM, Daniel McDonald <notifications@github.com<mailto:notifications@github.com>> wrote:


I read the post before I responded. We've always deferred identifier remapping to as close to the tool as necessary (e.g., the app controllers); the plugins are a new take on an old problem. The sample information is not a plugin though. QIIME either is or is not MIENS complaint and I really don't feel that there is a grey area there. If it is not MIENS compliant, then it disregards a widely accepted community standard and we're just scratching the surface of interoperability issues that this introduces.

**Comment by ebolyen** [comment]
Thanks for the links everyone!

[Supplement 3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367316/#SMtitle) of the MIMARKS paper uses underscores for the sample identifiers (unless I am completely mistaken). One of the example sheets also uses a dash character (pmoA) , and another fails to name the sample at all (dsrA).

Futhermore, QIIME 2 can have sample IDs that are both compliant and a superset. Reiterating @jairideout's point, there is nothing in QIIME 2 that prevents you from using MIMARKS (you should use it!).

**Comment by antgonza** [comment]
Just to have it the thread, are there any restrictions for the Qiime2 sample names? My concern is special characters or spaces, when thinking in writing per sample FASTQs for deposition (SRA/EBI). In general, when you submit (which is always per sample, per experiment, per sequencing run) you name your files as your sample name and having those special chars could become problematic.

**Comment by jairideout** [comment]
> are there any restrictions for the Qiime2 sample names?

There's certain special characters that are restricted in sample IDs and column names, see [this section of the metadata tutorial](https://docs.qiime2.org/2017.8/tutorials/metadata/#metadata-from-a-text-file) for details.

**Comment by antgonza** [comment]
Thanks, perhaps worth expanding what etc means, cause based on that description I'm not sure if "my_sample_name\t" or "my_sample%$@~&|" are valid. In fact, perhaps it will be easier to say what's expected like [a-A][z-Z][?????] .

**Comment by wasade** [comment]
Users likely want to do things outside of QIIME2

**Comment by wasade** [comment]
...misclick, my apologies

**Comment by antgonza** [comment]
As you can imagine finding tools that have sample restrictions is pretty hard but found some:
1. RDP via phyloseq doc, [see 4.8, specifically 4.8.3](https://www.bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-basics.html) - honestly, I _think_ RDP is the source of this "rule".
2. [Galaxy tool ids are underscore aware](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-ids). They use underscores to separate their tools.
3. [TruSeq Amplicon](https://support.illumina.com/help/BS_App_TruSightTumor170_OLH_1000000028435/Content/Source/Informatics/Apps/WkflReq_appT170.htm)
4. split_libraries_fastq.py - QIIME, this still needed for anyone that has non EMP primers/wet-lab work and wants to run QC and demultiplexing. Important for Qiita. 
5. [redbiom](https://github.com/biocore/redbiom)
6. deblur - what triggered this discussion
7. Not a tool but this caught my eye - way more results in Google that I would had expected: all the documentation and tutorial surrounding how to create valid mapping files for QIIME. In other words, this is a really spread "rule".
8. Have to also add it :| [here](https://msdn.microsoft.com/en-us/library/ms182245.aspx)

**Comment by wasade** [comment]
Thanks, Antonio. I heard back from Pelin as well, who indicated that sample_name in MIENS/MIMARKS/MIxS does not have character restrictions. #SampleID is not a required attribute (thus no character restrictions). Unfortunately, QIIME was wrong on these points for years

**Comment by rob-knight** [comment]
Thanks; that is unfortunate and clearly this time around we should document where information about standards compliance comes from.

So in the light of this new information, the main things we should care about with respect to users are:

1. Will they be able to deposit their data easily in a standards-compliant way? This is important because otherwise their life is hell at the end of the analysis, and we need to support analysis end-to-end including data archiving. Antonio is testing what EBI will accept in terms of special characters for a deposition now.

2. Will they be able to export to other tools that have long made assumptions about the identifiers that QIIME is documented to emit?

Of these, 1. is much more important.

Since the identifier issue is not a standards issue, contrary to the QIIME 1 documentation, I agree that it should be handled via remap but both this and checking that the metadata are standards compliant for deposition are high priority as the decision to change the identifier spec will cause all sorts of pain for developers and users.

On Sep 22, 2017, at 7:15 AM, Daniel McDonald <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, Antonio. I heard back from Pelin as well, who indicated that sample_name in MIENS/MIMARKS/MIxS does not have character restrictions. #SampleID is not a required attribute (thus no character restrictions). Unfortunately, QIIME was wrong on these points for years

**Comment by antgonza** [comment]
For 1. I underestimated how hard testing this can be. The problem is that all our code relies on the sample names being the file names for deposition (sample1, file deposition sample1.fastq.gz). Thus, actually testing this, will mean that I would have to rewrite those sections, so perhaps it's better to wait to have the remap ready (BTW is there an issue for this and do you need help with the solution?). Anyway, as @wasade mentioned, sample_name (and any other metadata field) have basically no restrictions so if we have a remap and the submission code uses that remap value for the sample names, we should be fine for submissions.

**Comment by rob-knight** [comment]
I agree that if it will take more time to verify that the remap is needed than to implement the remap, it would be a good idea to focus on the latter…


On Sep 27, 2017, at 5:39 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>> wrote:


For 1. I underestimated how hard testing this can be. The problem is that all our code relies on the sample names being the file names for deposition (sample1, file deposition sample1.fastq.gz). Thus, actually testing this, will mean that I would have to rewrite those sections, so perhaps it's better to wait to have the remap ready (BTW is there an issue for this and do you need help with the solution?). Anyway, as @wasade<https://github.com/wasade> mentioned, sample_name (and any other metadata field) have basically no restrictions so if we have a remap and the submission code uses that remap value for the sample names, we should be fine for submissions.
