### ISSUE TITLE
Handle reserved words in `Metadata.ids(where=...)`

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#353]
[This came up on the forum](https://forum.qiime2.org/t/group-not-accepted-as-metadata-category/1590). It looks like reserved SQL words cannot be used as an identifier. 

For example, this command:
```
qiime feature-table filter-samples --i-table table.qza --m-metadata-file sample-metadata.tsv --p-where “Group=‘1’” --o-filtered-table test.qza
```
raises:
```
Selection of IDs failed with query: SELECT “#SampleID” FROM metadata
WHERE Group=‘1’ GROUP BY “#SampleID” ORDER BY “#SampleID”;
```
which also isn't very obvious.

It is possible quoting the identifier will help.

**Comment by thermokarst** [comment]
[Related discussion](https://github.com/qiime2/q2-feature-table/issues/154).

Maybe this warrants splitting into a more general-issue in the future, but for now this seems like a good place to move the discussion.

**Comment by antgonza** [comment]
Cool, thanks for pointing to the right place and the difference between single and double quotes. BTW I noticed that cause '' didn't yield what I was expecting but "" did. Note that as far as I can tell "" doesn't actually raise an issue about the non existing column.

**Comment by thermokarst** [comment]
That totally makes sense! There are a bunch of "gotchas" here, and we can certainly do a lot more to help folks out with this! RE: "", please see my discussion [here](https://github.com/qiime2/q2-feature-table/issues/154#issuecomment-343530000) about why that is happening! Thanks for this example, it is a good one for this discussion.

**Comment by rob-knight** [comment]
Because this is such a chronic and recurring issue, should we look into a standard, global method to escape text throughout qiita, then make it pretty in the web interface for display to the user?

On Nov 10, 2017, at 9:12 AM, Matthew Dillon <notifications@github.com<mailto:notifications@github.com>> wrote:


That totally makes sense! There are a bunch of "gotchas" here, and we can certainly do a lot more to help folks out with this! RE: "", please see my discussion here<https://github.com/qiime2/q2-feature-table/issues/154#issuecomment-343530000> about why that is happening! Thanks for this example, it is a good one for this discussion.
