### ISSUE TITLE
[Question] Any methods for creating .qza files from pandas dataframes?

### ISSUE THREAD

**Issue by jolespin** [qiime2/qiime2#401]
I have all of my data in tab-separated files that import into pandas.  I want to try and use some of the methods in the `Artifact API` to speed up my workflow instead of running the separate modules outside of my working environment.  It looks like most of the methods I am interested in like `differential_abundance` takes in `*.qza` files which I am unfamiliar with atm. 

**Are there any tutorials that show how to either convert a `pd.DataFrame` or read a table into a `qza` data structure?**

**Comment by ebolyen** [comment]
Hey @jolespin! That's a really good question for the [QIIME 2 Forum](https://forum.qiime2.org/) we'd love to see you there!

In short, it's going to depend on what types your method needs. But you can look at [this thread](https://forum.qiime2.org/t/calculate-unweighted-unifrac-with-artifact-api/4162) for some ideas. Otherwise, please feel free to create a topic on the forum (where more than just the developers can help), thanks for reaching out!

**Comment by jolespin** [comment]
Perfect, I didn't know about the forum but will definitely use it from now on!
