### ISSUE TITLE
Misunderstood parameter of NCBI BLAST impacts the correctness of bioinformatics workflows

### ISSUE THREAD

**Issue by danwiththeplan** [qiime2/qiime2#412]
NCBI-BLAST is used internally by QIIME2 as I understand it. Does this recent publication affect any part of QIIME2?

https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty833/5106166

**Comment by nbokulich** [comment]
Thanks for asking @danwiththeplan .

**The short answer** is yes but no. Yes because we use BLAST+ in a few places, but no because those are all fairly thin BLAST wrappers where we intentionally expose BLAST functionality directly (including the max_target_seqs param). And because there are alternative methods available, as I will explain below.

**The long answer**. We have been familiar with that BLAST+ issue for a while now, and there has been a bit of discussion of that on the QIIME2 forum. This is used by QIIME 2 in two places, but only the first will actually impact users:

1. `q2-feature-classifier` has a `classify-consensus-blast` method, which uses BLAST+ for sequence alignment against a reference database, followed by a LCA consensus taxonomy method. That method *will* be impacted because it uses the max_target_seqs parameter explicitly  via the maxaccepts parameter. However, this parameter can be switched off (I believe, by setting to 0) or set to a very high value to mitigate this effect; increasing the perc_identity parameter value will also mitigate this effect. The default setting for max_target_seqs is 10, which is already reasonably high with amplicon reference databases, and performs quite well [according to our benchmarks](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0470-z). We also have an [open issue](https://github.com/qiime2/q2-feature-classifier/issues/112) to make this behavior more transparent in q2-feature-classifier even if it is not in the BLAST+ docs! Finally, for any users who are concerned that this parameter is bad news for them but insist on using an alignment-based taxonomy classifier, they can instead use the `classify-consensus-vsearch` method, which uses vsearch for alignment but otherwise works the same and performs very similarly. The vsearch docs are much more explicit and as far as I know the maxaccepts parameter does work as everyone on the planet would intuitively expect this parameter to work!

2. `q2-quality-control` uses BLAST+ for alignment in the `exclude-seqs` method. However, that is a filter exclusion method used to remove (or retain) sequences that match a set of reference sequences within X percent identity, so it does not matter WHAT the sequence is aligning against, just as long as there is something similar enough in the database! So the `max_target_seqs` param is actually set to 1 for that method for that reason. The onus is on the user to make sure that they are using an appropriate reference database (e.g., that really does represent sequences they want to exclude/keep)

For both of these, the intention is to wrap BLAST as faithfully as possible for the alignment step — the reason being that most users are probably more familiar with BLAST than they are with QIIME. So we don't want to tinker with how these parameters behave, so that the method does just what users "want" (in quotes because obviously the BLAST+ `max_target_seqs` param does not really do what most users want/expect based on the BLAST+ docs description!).

I hope that makes sense! I will close this issue because this is not a QIIME-wide issue, but please feel free to reply even once it is closed. If you have ideas for improvement or additional concerns, please either open an issue in the appropriate GitHub repo (now that you know the plugins that use BLAST+), or take to the forum for more general discussion.

Thanks!

**Comment by danwiththeplan** [comment]
Great clarification thanks.
