### ISSUE TITLE
Installation by PyPI (pip3) for ARM environment

### ISSUE THREAD

**Issue by junaruga** [qiime2/qiime2#443]
**Improvement Description**
This is a suggestion for a feature.

Seeing the qiime2 installation document, there is a way to install `qiime2` by conda.
https://docs.qiime2.org/2019.1/install/
But right now conda does not work on ARM environment ( https://github.com/conda/conda/issues/8297 ), it is possible to provide the `qiime2` PyPI package in a case of using `qiime2` on ARM environment?
There is the `qiime` package. But no `qiime2` package there.
https://pypi.org/project/qiime/

**Questions**
Or do you like this is suggested on https://forum.qiime2.org/c/user-support ? Thanks.

**References**
1. https://docs.qiime2.org/2019.1/install/
2. https://github.com/conda/conda/issues/8297
3. https://pypi.org/project/qiime/

**Comment by ebolyen** [comment]
Hi @junaruga,

That's a fair question, and we don't have anything against ARM, but we don't really have the bandwidth to accomplish this (read: community help would be appreciated).

As to using pip, we're a little less excited about that as it represents a new way for users to potentially inconsistently install QIIME 2. As an example, consider q2-dada, it is a Python and R plugin. Conda works really well for synchronizing the version of bioconductor and any Python dependencies needed. This is pretty well beyond the scope of pip, which means while pip would install the Python half, you would be left figuring out the R side. There are many other plugins which are not exclusively Python which have this same problem.

Something that might be viable is a strictly source install of everything. This does leave you on the hook for each dependency, but it's less likely that someone would be left in a situation they cannot get themselves out of as the barrier to entry is a lot higher than pip. Since we have conda recipes in each plugins repo, the dependencies are relatively well documented, we just haven't put a lot of effort into this installation path, as we do think conda is the better approach generally.

---

As for ARM on conda, this looks really interesting: https://github.com/archiconda/
Perhaps a long term goal could be ARM on conda, we have an automated build process which we can adapt relatively easily. But the larger problem is still all of the dependencies,  so again we'd need community support to make this viable given our relatively limited resources.

**Comment by junaruga** [comment]
> As an example, consider q2-dada, it is a Python and R plugin. Conda works really well for synchronizing the version of bioconductor and any Python dependencies needed. This is pretty well beyond the scope of pip, which means while pip would install the Python half, you would be left figuring out the R side. There are many other plugins which are not exclusively Python which have this same problem.

Thank you for the detail information!

Your concern makes sense for me.
I think right now the right way to install `qiime2` on ARM is not `pip` (PyPI) package but trying to install the ARM on conda (`archiconda`) contributing to conda or creating the deb package `qiime2` as a Debian/Ubuntu pre-built package that considers every dependencies like conda.

Right now there is `qiime` deb package on Debian. But no `qiime2` package.
https://tracker.debian.org/pkg/qiime
And I might try to create `qiime2` package when I have a time.

And I am very happy to contribute a source code to this repository as a community help when something is necessary to run it on ARM.

**Comment by Oddant1** [comment]
This might still vaguely be a future target, but we're cleaning up the issue tracker right now, and I'm going to close this for now
