### ISSUE TITLE
Allow Metadata constructor(s) to optionally strip whitespace

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#478]
**Improvement Description**
A kwarg in the various Metadata constructors to strip whitespace in all columns could be really convenient for transformers et al.

**Current Behavior**
Whitespace is not stripped.

**Proposed Behavior**
If some kwarg (say, `strip_whitespace`) was True, the MD constructor would strip whitespace.

**Questions**
1. This could also just be the default behavior, right? Am I missing something here?

**Comment by Oddant1** [comment]
How should this work if we view an artifact as metadata? We could add a `strip_whitespace` parameter to the `view` method of artifacts, but that doesn't really make sense does it? Because most view types wouldn't use it. Should we just except if they try to strip_whitespace while viewing as something other than metadata?

**Comment by thermokarst** [comment]
> How should this work if we view an artifact as metadata?

I was envisioning this behavior being specific to the individual transformers in question, although the more I think about this, the more I like the idea of changing the default behavior to always strip, in all contexts. What am I missing here, @ebolyen?

**Comment by ebolyen** [comment]
Yeah I agree that this could definitely be the default behavior. I know that there was a distinction between the file-format and the in-memory representation, but I don't remember why (if for any particular reason) the constructor was not allowed to deal with this.

Some other differences between the two that might jog memories:

  1. float parsing is custom to the file version, whereas datatypes are taken as granted for the constructor
  2. jaggedness is only handled in the file version, the memory version can't have it in the first place

**Comment by Oddant1** [comment]
As far as making this the default behavior is concerned, do we still want this to be a parameter that just defaults to `True` or do we just want this stripping to happen under the hood?

**Comment by thermokarst** [comment]
> do we still want this to be a parameter that just defaults to True

My vote is for a parameter that defaults to `False`. User-facing metadata construction will remain the same (by default). Metadata transformers will be updated to use `strip_whitespace=True`, to fix things like https://github.com/qiime2/q2-types/issues/179.

> are we trying to strip only the column headers, or are we trying to strip every string element of the metadata?

I think stripping values is the most important thing at the moment. Perhaps this could be evidence for a more fine-grained parameter `strip_whitespace='values'` vs `strip_whitespace='all'` vs ad naseum.

**Comment by Oddant1** [comment]
So the options for `strip_whitespace` now become say "values", "columns", "none" and "all". All of the transformers default to "all" and the constructor defaults to "none"?

**Comment by thermokarst** [comment]
Perhaps. What do you think?

**Comment by Oddant1** [comment]
I'm not sure I understand the need to the granularity between stripping only the column headers or only the values within the columns, but I'm also not sure I understand why we can't have leading or trailing whitespace in `CategoricalMetadataColumns` or anything else. Given the error message in qiime2/q2-types#179, it does seem as though stripping the values within the columns is most pertinent, but that's only one particular issue. I don't see any reason not to also allow for stripping of column headers especially since it would be very easy to implement.

**Comment by Oddant1** [comment]
Alternatively, if we wanted the same effect we could have two parameters `strip_columns` (or maybe `strip_column_headers`) and `strip_values` and make both booleans

**Comment by thermokarst** [comment]
Don't forget "ids", too. They aren't columns or values.

**Comment by Oddant1** [comment]
ids in this case are the index correct? I think having individual booleans for whether or not each of them should be stripped is probably cleaner than trying to have the same effect with a mess of different string values. Especially if we're now having three different categories.

**Comment by thermokarst** [comment]
Hmm, you think so? There is no right answer here, but wondering _why_ you think that.

**Comment by Oddant1** [comment]
If we tried to do it with one `strip_whitespace` parameter that took a string with now 8 possible different values there is more potential for user error, say we made the string for stripping ids and column headers `id_header` now if they enter `header_id` everything explodes. This also turns our checks into something like.
```
if strip_whitespace == 'id_header' or strip_whitespace == 'id' or strip_whitespace == 'all':
    Strip whitespace in ids
```
This could be somewhat simplified to
```
if 'id' in strip_whitespace or 'strip_whitespace' == 'all':
    Strip whitespace in ids
```
Which would accept such garbage as 'awjobgahwfid', but would have less potential for user error as it would also accept `header_id` or anything else that would sensibly be meant to strip ids (we would probably want to to `.lower()` their string as well). If we do it with three booleans, the user does have to set three booleans (which could be kind of annoying) but there's much less potential for error and the checks become as simple as
```
if strip_ids:
    Strip whitespace in ids
```

**Comment by thermokarst** [comment]
> there is more potential for user error, say we made the string for stripping ids and column headers id_header now if they enter header_id everything explodes

Very true, that is why it is our job to help protect the user from these kinds of bombs! 

>  but there's much less potential for error and the checks become as simple as

Fair point! But, who is this optimizing the API for? And, who do _you think_ we should be optimizing the API for?

**Comment by Oddant1** [comment]
We should definitely optimize for the user, but which is optimal for the user is subjective. Three booleans is much more transparent in what it's doing in my head than a single string value even if it could potentially take more time to set. If we go with the single string, I'm imagining we would want some sort of help text explaining the intended values (something like "none", "all", "ids", "headers", "values", "ids_headers", "ids_values", "headers_values") as opposed to saying something like "your options are 'none', 'all', or any string containing the substrings 'ids', 'headers', or 'values' regardless of which implementation of string checking we were to use. And then of course we would explain what actually gets stripped for each of these values. The best way to do it overall in theory is probably something similar to the second implementation above where we just check for a key value in a string instead of making sure the string exactly matches whatever the "intended" input is, but that does introduce potential sources of confusion. Either you explain it to them as something like "if your string contains 'id' ids will be stripped" and so on which could confuse them, or you present them with a list of 'acceptable' values and they are potentially left confused when something not on that list works. The first option has the messiest logic and is the most prone to user error due to the rigidity of what it will except, so it's kind of the worst of both worlds, but it has the least potential for confusion of the two string options. Basically the way I see it. Boolean option, least error prone, least confusing, best logic, most time consuming. Second option, middle error prone, most potential confusion, decent logic, theoretically takes the same amount of time as the first option. First option, most error prone, tied for least confusing, ugliest logic, and again theoretically tied with the second option for time.

**Comment by thermokarst** [comment]
Thanks for explaining your thoughts! I was with you up until you got into "substrings" --- I just want to clarify, we wouldn't be searching for substrings in _any_ proposed solution ("your options are 'none', 'all', or any string containing the substrings 'ids', 'headers', or 'values'"). Let's take a step back to make sure we are on the same page:

Whitespace stripping involved taking a string and removing any leading or trailing whitespace from the string.

There are several "elements" to Metadata, all of whom _could_ be subjected to whitespace stripping, including the Metadata ID values, the Metadata column label values, and the Metadata column values themselves. 

We have two types of options on the table right now:

1. boolean parameters
2. a controlled vocabulary of "choices"

Are we on the same page?

**Comment by Oddant1** [comment]
Alright so completely throw out the substring option. Maybe the optimal solution is simply to go with the choices but make both `ids_headers` and `headers_ids` valid inputs for the same behavior?

**Comment by Oddant1** [comment]
It has been decided upon that all pieces of the metadata will be automatically stripped behind the scenes with no extra parameter(s) allowing for control over this behavior. This is to allow other methods to assume that all `Metadata` objects have been fully stripped.
