### ISSUE TITLE
Importing non-existent semantic type complains about missing directory format

### ISSUE THREAD

**Issue by thermokarst** [qiime2/qiime2#514]
**Bug Description**
When importing, if a user specifies a non-existent semantic type, QIIME 2 doesn't tell them that the type doesn't exist, instead it complains about the type not having a compatible directory format.

**Steps to reproduce the behavior**
```python
import qiime2
# Peanut[TheDog] is a made-up semantic type
qiime2.Artifact.import_data('Peanut[TheDog]', None)
...
TypeError: Semantic type Peanut[TheDog] does not have a compatible directory format.
```

**Expected behavior**
I think seeing a message along the lines of "No such semantic type as Peanut[TheDog] registered in this deployment of QIIME 2" would be a good start.

**Questions**
1. `qiime2.sdk.parse_type` is implicated in this --- should this util perform this validation/verification, or should it stay in `import_data` (or be elsewhere altogether)?

**Comments**
1. This problem is probably limited to lazy evaluation of the type (specifying the string value`'Foo'` vs the type object `Foo`).

**References**
1. [Original forum post](https://forum.qiime2.org/t/help-importing-a-concatenated-fastq-file-as-multiplexed-paired-end-barcode-in-sequence/13035)

**Comment by gregcaporaso** [comment]
I just ran into this too and it caused some head scratching for a few minutes.

**Comment by Oddant1** [comment]
[This](https://github.com/qiime2/qiime2/blob/af777c65b1aef7fa3b0dc3e1a87d423c26eb7be4/qiime2/sdk/plugin_manager.py#L369) looks to be the implicated code. If I am reading what this function does correctly, we can actually just change the current error message can't we? Because it looks to me like that for loop is checking if the artifact class is registered not if it has a directory format.

**Comment by gregcaporaso** [comment]
That sounds right to me @Oddant1.
