### ISSUE TITLE
InternalDirectory's rename() will fail on python 3.8

### ISSUE THREAD

**Issue by pschuprikov** [qiime2/qiime2#520]
**Future Bug Description**
In python 3.8 __rename()__ method of __Path__ object returns a target path https://github.com/python/cpython/blob/dc56f5f48866bf3c5412642bba00890d9a090cfb/Lib/pathlib.py#L1354 As a result, __rename()__ called on __InternalDirectory__ leads to construction and _destruction_ of a "temporary" __InternalDirectory__ object https://github.com/qiime2/qiime2/blob/4642a6be16b27cd6c71f264fc4f2ce7c984072e0/qiime2/core/path.py#L113 removing the target path https://github.com/qiime2/qiime2/blob/4642a6be16b27cd6c71f264fc4f2ce7c984072e0/qiime2/core/path.py#L99

**Steps to reproduce the behavior**
1. Run build tests with python 3.8

**Expected behavior**
Tests pass

**Computation Environment**
- OS: Debian (experimental)
- QIIME 2 Release: 2019.10

**References**
1. Bug on debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950842

**Comment by ebolyen** [comment]
Thank you so much for the report! We will need to override that probably...

**Comment by tillea** [comment]
Any progress on this?  We want to update the Debian package of qiime2 and Debian has Python3.8 so it would be great if you could come up with a patch.
Thanks a lot, Andreas.

**Comment by thermokarst** [comment]
Hi @tillea - QIIME 2 currently only supports execution in Python 3.6 environments. Python 3.7+ is on our radar, but likely won't be addressed until some time in 2021. Since we only support QIIME 2 in conda-based environments, using an old version of Python doesn't represent much of a problem for our users, since they can jump between multiple conda envs (generally speaking).

**Comment by tony-travis** [comment]
Hi, @thermokarst I'm last-man-standing on the Bio-Linux project and I've worked with the Debian-Med team for a long time. I think @tillea is right that it would be good to validate QIIME against the current version of Python 3.8 supported by Debian and Ubuntu. I'm currently running QIIME under Bioconda to work around Python incompatibilities and conflicts with more recent versions of the supporting software installed from the Debian-Med "med-bio" packages. It would be great to have a version of QIIME that is compatible with the "med-bio" packages and installed from a .deb package. Tim Booth, who used to be the lead developer on the Bio-Linux project, did create a QIIME .deb package for Bio-Linux, but I could never validate it against the QIIME test suite and I created my own wrapper before discovering Bioconda.

**Comment by thermokarst** [comment]
Hi @tony-travis! As I mentioned above to @tillea, 3.7+ support is on our radar, but we won't have time to address it until some time in 2021 (this is just an estimate). If you're interested in contributing we would love a hand! We are currently building a new CI system (for distributed community plugin builds), which would ideally support building against multiple python targets. Relevant to this discussion though (cc @tillea), the notion of the "[core distribution](https://docs.qiime2.org/2020.8/install/#qiime-2-core-2020-8-distribution)" of QIIME 2 is likely not going to exist past the next year or so - with [our new CI system](https://forum.qiime2.org/t/qiime-2-czi-essential-open-source-software-for-science-announcement/12604) we are hoping to enable "roll-your-own" plugin packs, where users will be able to pick and choose what plugins are installed in a particular conda environment, in a way that allows us to integration-test all of the secondary and tertiary dependencies. I don't see an apparent solution here for supporting deb packages, though, because QIIME 2 plugins aren't strictly composed of Python components/dependencies, they rely heavily on conda-build recipes, and in the [not-so-distant future, we anticipate supporting R-based plugins](https://forum.qiime2.org/t/qiime-2-is-now-funded-by-the-national-cancer-institute-and-lots-of-exciting-new-things-are-coming/16067), to boot (that last one might not be a real challenge, but just want to point that out - it gets more complicated). That's not to say that we aren't interested in supporting these other build types (like deb packages), its just challenging to envision how to accomplish it in a way that plays nicely with conda, and without a "core" distribution of plugins, I'm not sure what would be good candidates for bundling into something like Debian-Med, etc.

**Comment by tillea** [comment]
Hi,
if you want to hear my opinion about your decision to support Python 3.7 I'd like to recommend to rather focusing on Python 3.9 which will become default in major distributions.  Keeping compatibility to older versions in mind is for sure sensible (as you wrote "multiple python targets").  I'm also not sure whether relying on Conda as default means to distribute QIIME-2 is a good idea since there might be potential users out there who want to use your software without an additional packaging system on top (for whatever reason).  I can confirm that one member of our packaging team will have a look at a Python 3.8 / 3.9 port of the currently released code base.  We will let you know if there might be some promising patches for your inspection.
Kind regards, Andreas.

**Comment by emollier** [comment]
Hello,

I've been working on a targeted patch set which covers at least the test suite for python versions 3.8 and 3.9.  The patches are available here after for the moment, but I can ready a proper merge request in the coming week, if you deem this more convenient:
    https://salsa.debian.org/med-team/qiime/-/blob/master/debian/patches/python3.8.patch
    https://salsa.debian.org/med-team/qiime/-/blob/master/debian/patches/python3.9.patch

Please be aware that I do not have a python 3.7 installation readily available at the moment, so couldn't make sure at 100% that the changes were non breaking; semantically they shouldn't hurt, hopefully.

Kind Regards,
Étienne.

**Comment by thermokarst** [comment]
Thanks @emollier! We still don't support any other versions of Python besides Python 3.6. When we add support for newer versions of Python we will review these patches then.

**Comment by Oddant1** [comment]
QIIME 2 uses Python 3.8 now, and this does not appear to be an issue anymore.
