### ISSUE TITLE
tabulate fails inscrutably when passed a csv

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/qiime2#537]
**Bug Description**
`qiime metadata tabulate` produces an `unrecognized ID column name` error when passed a .csv, because it is disregarding the commas as separators and gluing all columns together. This is confusing to newer users.

**Steps to reproduce the behavior**
1. Download and unzip this guy: https://data.qiime2.org/2020.2/tutorials/read-joining/fj-joined.zip
2. In a QIIME 2 environment, run:
```
qiime metadata tabulate --m-input-file fj-joined/manifest --o-visualization metadata
```
3. Error, apparently caused by metadata combining all comma-separated columns into one.

**Expected behavior**
Either
1. Error, saying metadata tabulate only works with `.tsv`
2. Gracefully handle `.csv` tabulation, silently, or by adding an additional parameter that defaults to `.tsv`

**Screenshots**
![image](https://user-images.githubusercontent.com/39198770/82079112-2698d600-9697-11ea-9fdb-b3b58d6710b1.png)

**Computation Environment**
- OS: LinuxMint 19.3
- QIIME 2 2020.2

**Questions**
1. Are old (V1) `SingleEndFastqManifestPhred33` files are the only thing blowing this up? If so, a good error message might be sufficient. 

**References**
[forum xref](https://forum.qiime2.org/t/problems-about-analyzing-joined-reads-using-qiime2/14950)

**Comment by thermokarst** [comment]
> Are old (V1) SingleEndFastqManifestPhred33 files are the only thing blowing this up?

No, anything that is not a valid TSV will error.

> Error, saying metadata tabulate only works with .tsv

The problem is that `.tsv` isn't a defined file format, generally speaking. TSV is mostly convention based (you can't even use the extension to confirm if its TSV or not, you have to parse the whole document, which is what is happening in the error message above).

> Gracefully handle .csv tabulation

The metadata spec only supports TSV (and pandas dataframes), and I would prefer to keep it that way for now. I think adding new metadata-spec compliant file formats is a can-of-worms for another day.

Perhaps we can move the last line up in to the top of the error message? That might help point people towards a solution.

PS - I move this over to the framework, since this doesn't really have anything to do with metadata tabulate - the error message is coming straight from the framework.

**Comment by thermokarst** [comment]
PS - I think "inscrutably" is a little bit unfair of a word to use there - the error message has a lot to say, but I don't think that means its impenetrable (its actually all written-out prose, which is a huge step up from a traceback of doom). I think with a little bit of tweaks to the verbiage we can streamline things a bit!

**Comment by ChrisKeefe** [comment]
Agreed, @thermokarst. Just the first word that approximated the situation. Unless you're itching to have this wrapped up soon, I'm going to self-assign and mull over how/if text changes can clarify the situation after `div-lib` is successfully covering `core-metrics`

**Comment by thermokarst** [comment]
> The problem is that `.tsv` isn't a defined file format, generally speaking. TSV is mostly convention based

Saw this on Hacker News today: http://thomasburette.com/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/
