### ISSUE TITLE
feature: interactive phylogenetic tree

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [qiime2/qiime2#56]
I've started working on a [d3.js based phylogenetic tree viewer](https://github.com/ConstantinoSchillebeeckx/phylogram_d3) which allows for dynamic interaction through an OTU map file.

Just started working on it so it's got a ways to go, but I thought it might be useful to others.
![tree](https://cloud.githubusercontent.com/assets/8518288/16153111/8a52f146-346a-11e6-93a7-c229df81fd21.png)

**Comment by jairideout** [comment]
@ConstantinoSchillebeeckx thanks for getting in touch, this looks useful! We are actively working on adding visualization support to the QIIME 2 framework so that plugin developers can register custom visualizations. If you're interested in hooking this up to QIIME 2, we'd be happy to work with you once visualization support is in place (likely end of July, after SciPy 2016 and the initial alpha release).

**Comment by ConstantinoSchillebeeckx** [comment]
Excellent, I'll stay posted.  Is there any documentation or place where I can start reading up on registering custom viz?

**Comment by ebolyen** [comment]
@ConstantinoSchillebeeckx not yet, in fact the PR which is kicking this off was just merged (https://github.com/qiime2/qiime2/pull/57). We'll have an example plugin which we will be able to link to you soonish (next week tentatively). 

But the basic idea is you will register a function which accepts some input artifacts, parameters, and a `data_dir` where you will write an `index.<ext>` file, where `<ext>` could be anything reasonable (like `.html`, `.png`, `.pdf`, `.svg`, `.tsv`, etc...). Because this is all very much still in motion we would be super interested in your early feedback as we get this API in place.

More details soon!

**Comment by ebolyen** [comment]
Just to update you @ConstantinoSchillebeeckx, we've got the fundamental pieces in place, at this point we still don't have any docs, but you can see the Emperor plugin [here](https://github.com/ElDeveloper/q2-emperor).

**Comment by ConstantinoSchillebeeckx** [comment]
Excellent, I'll start looking at the Emperor plugin and get things rolling.

**Comment by ConstantinoSchillebeeckx** [comment]
Hi gang, I've started a first crack at putting together a [plugin](https://github.com/ConstantinoSchillebeeckx/q2-phylogram); however (in the absence of any documentation) I can't get the proper syntax down for the ```plugin.visualizers```.  Could someone take a look?

**Comment by gregcaporaso** [comment]
@ConstantinoSchillebeeckx, great to hear that you're making progress with this! We actually do have some draft documentation up for this now - see [here](https://github.com/qiime2/qiime2/wiki/Creating-a-QIIME-2-plugin). 

The specific issues I see with this now are:

* [Your ``Newick`` input](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/640ebdd51b9f59d1664ae83698febf85272a6fef/q2_phylogram/plugin_setup.py#L124) needs to be described with a semantic type - in this case ``q2_type.Phylogeny``. In order for this to work, you're going to need to  create a new data reader in your plugin that gets registered on ``Phylogeny``. This code should work for that - I'd put that in your ``plugin_setup.py`` (but technically it can go anywhere):

```python
import Bio

def tree_to_biopython_phylo(data_dir):
    with open(os.path.join(data_dir, 'tree.nwk'), 'r') as fh:
        return Bio.Phylo.read(fh, 'newick')

plugin.register_data_layout_reader('tree', 1, Bio.Phylo, tree_to_biopython_phylo)
```

* [Your ``OTU_metadata`` input](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/640ebdd51b9f59d1664ae83698febf85272a6fef/q2_phylogram/plugin_setup.py#L125) also needs to be described with a semantic type, but we don't have one yet for this. We're going to be sprinting to add new types this week at the SciPy 2016 sprints, and this one is on our list to add. Can you describe exactly what you're expecting to be in that file? We're thinking that this will end up being viewed as a ``pandas.DataFrame``, so want to make sure that it's compatible with what you're needing to do. 

* In your [view API signature](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/640ebdd51b9f59d1664ae83698febf85272a6fef/q2_phylogram/plugin_setup.py#L72), you should annotate as follows:

```python
def make_d3_phylogram(output_dir: str, Newick: Bio.Phylo, OTU_metadata: pd.DataFrame):
```

(Note: the annotation for ``OTU_metadata`` might change, pending our sprint this weekend. We'll let you know.)

* In ``setup.py``, [your ``entry_point``](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/blob/640ebdd51b9f59d1664ae83698febf85272a6fef/setup.py#L23) should be changed to ``qiime.plugins``. 

* I recommend that you call our ``Newick`` input ``tree`` (instead of ``Newick``, as in the future, you might want to support other formats). Also, I recommend lowercase ``otu_metadata`` instead of ``OTU_metadata`` (just easier to type and more Pythonic).

Thanks for being willing to work on this pre-alpha! Our alpha release should go out tomorrow, and all of this will stabilize a bit then.

**Comment by ConstantinoSchillebeeckx** [comment]
Thanks @gregcaporaso - that's indeed what I needed.

First, to answer your question: the `otu_metadata` is the equivalent of a [standard QIIME mapping file](http://qiime.org/documentation/file_formats.html#metadata-mapping-files) however each row represents an OTU instead of a sample.  It simply associates metadata such as taxonomy, etc to the OTU.  A `pandas.dataframe` semantic type is just fine, in fact I'm already using it that way.

I've gone ahead and followed the plugin guidelines and have been able to install it locally:
```
Installing collected packages: q2-phylogram
  Running setup.py install for q2-phylogram ... done
Successfully installed q2-phylogram-0.0.0.dev0
```
However, when I check the list of installed plugins with `qiime --plugins` I see:
```
Installed plugins:
 diversity 0.0.0-dev (https://github.com/qiime2/q2-diversity)
 feature-table 0.0.0-dev (https://github.com/qiime2-plugins/q2-feature-table)
 types 0.0.0-dev (https://github.com/qiime2/q2-types)
 emperor 0.0.0 (https://emperor.microbio.me)
```

Thoughts?

**Comment by jairideout** [comment]
@ConstantinoSchillebeeckx I submitted a pull request on your repo [here](https://github.com/ConstantinoSchillebeeckx/q2-phylogram/pull/2) that should fix the plugin registration issues you were having. I included more details in the pull request's description. Can you test it out and see if that fixes the issues you're having?

**Comment by ConstantinoSchillebeeckx** [comment]
closing as plugin setup is [completed](https://github.com/ConstantinoSchillebeeckx/q2-phylogram)
