### ISSUE TITLE
warn if recommended artifact file extension isn't used

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime2#7]
`Artifact` and `Visualization` should warn when `load` or `save` is called with a file path that doesn't have the recommended file extension. This issue depends on #6.

**Comment by jairideout** [comment]
#106 added a warning when saving, does it also make sense to warn the user when loading with the wrong extension?

**Comment by jakereps** [comment]
@ebolyen and I talked about that, and it sounded like it made the greatest impact towards saving, as that can affect usage throughout the interfaces, because as of now the studio won't even acknowledge a non-`.qza/v` file, and the cli doesn't seem to care what you give it as long as it is loaded in without issue (e.g. a valid Artifact), (unless that itself is an issue?) but we weren't too sure on the warning for loading. I can definitely add it in though if it's something that should be there?
