### ISSUE TITLE
Recycle uses dangling references in cache induced by OS X tmpdir cleanup

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime2#738]
**Bug Description**
Dangling references cause an error when loading an artifact via `recycle`.
This is usually going to be a result of the `data/` directory being cleaned without the reference also getting cleaned.
Because garbage collection opens all of the references, any timeout/last-modified counter is refreshed for references, but will not be refreshed for the directories within data (as only the dir-entries of `data/` are read, rather than each file).

**Steps to reproduce the behavior**
1. Use OS X
2. Run a failing command with default recycle argument.
3. Wait less than 2 days and run any other successful QIIME command (causes references from 2 to be read again).
4. Wait another day for OS X to delete the data directories from step 2.
5. Re-run the command from 2 with the same default recycle.

**Expected behavior**
We should either detect dangling references and delete them during GC, or tolerate dangling references and regenerate data from the source QZAs as needed.

**Computation Environment**
- OS: OS X
- QIIME 2 Release 2023.9

**Comment by ebolyen** [comment]
This is the issue @lizgehret ran into a few weeks ago (also discussed with @Oddant1)

**Comment by Oddant1** [comment]
What if we make it so that when we read the symlink from the recycle pool we also make sure poke the actual data? This should be doable right? This should keep them both from being reaped with only a tiny little gap for the data to be reaped out from under us after reading the symlink. This gap will basically always exist no matter what we do though.

(This is not resistant to deleting things out from the data directory by other means)

Additionally keep in mind the fact that because this is a recycle pool from a failed pipeline run we're talking about here some of the things referenced in the pool will be intermediate pipeline results and we won't have a .qza representing them anywhere, so we can't regenerate those from the source .qza because it doesn't exist.
