### ISSUE TITLE
plugin download no longer available

### ISSUE THREAD

**Issue by RobJamesRamos** [qiime2/qiime2#793]
I am one of the developers of a [LSU](https://github.com/c383d893/AMF-LSU-Database-and-Pipeline2) pipeline that heavily utilizes Qiime 2. We have a custom yml as part of our install script that is based on Qiime2-2024.2. We tested the pipeline extensively with the specific set of package versions that were in the current release. Right now we have a user [issue](https://github.com/c383d893/AMF-LSU-Database-and-Pipeline2/issues/6) that [rescript-2024.2.2-py38h6d1c77b_0.tar.bz2](https://packages.qiime2.org/qiime2/2024.2/amplicon/released/linux-64/rescript-2024.2.2-py38h6d1c77b_0.tar.bz2) is no longer available. The download link seems broken. I am hesitant to simply bump any version numbers since we would want to test the pipeline thoroughly before doing that. Is there anyone that can get that link working again?

**Comment by lizgehret** [comment]
Hey @RobJamesRamos, so from the issue you linked it looks like this user is attempting to download the 2024.2.0 version of RESCRIPt - this version is no longer available because we had to perform a patch release for this package (due to a couple of requisite bug fixes). So 2024.2.2 is the version that you'll want to use. This patch released version of RESCRIPt has been tested against the entire 2024.2 QIIME 2 Amplicon distribution, so you shouldn't have to worry about breaking things with this version bump.

Moving forward, if you have any questions regarding package use/etc, please reach out via our [user forum](https://forum.qiime2.org/) - this allows for better visibility on questions for our user community. Thanks so much!

Cheers 🦎
