### ISSUE TITLE
plugins should have a description that can be used by interfaces

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/qiime2#81]
It'd be nice to have short descriptions that could be used as help text. For example, here:

![screenshot 2016-07-08 14 16 03](https://cloud.githubusercontent.com/assets/192372/16701741/9c9b47c4-4516-11e6-8a95-f59a2a40fa4c.png)

Related to qiime2/q2cli#16

**Comment by jairideout** [comment]
It would be useful to have short and long descriptions, similar to actions, so that the CLI and other interfaces can choose how much detail to display. How about adding two new keyword arguments (to preserve backwards-compatibility): `short_description=None` and `description=None` ? `short_description` would be a single short sentence like what's displayed in your screenshot, and `description` is longer text that is displayed when passing `--help` to a plugin.

**Comment by gregcaporaso** [comment]
I like it.

**Comment by maxvonhippel** [comment]
So just a brief update on progress, I've set up my dev environment and read around 40% of the code from the 5 repositories.  I've added `short_description` and `description` to plugin.py with `=None` in the params so (as you suggested) we keep backward compatibility.  I'll do some tests and make sure nothing's broken but I mean I really see no reason why this would break anything.

It seems like the logical next step is to incorporate `description` and `short_description` into the code in appropriate places.  I can start by throwing in an extra argument to print the `short_description` tab'd across from the plugin name in the output from `--help` per @gregcaporaso's suggestion.  Are there any other particular places you can think of where these two values would definitely be worth printing?  Should I just read the code some more and see if I find anything?  Or should I just add the `short_description` print statement to the `--help` output as suggested, test to make sure nothing's broken, PR and call it a day?

**Comment by jairideout** [comment]
Thanks for working on this @maxvonhippel! I'd start by submitting a PR to this repo (the QIIME 2 framework) that includes the new `short_description` and `description` API and some unit tests. I can take the lead on reviewing and merging that PR.

After that, it'd be great to hook up to q2cli so that the short description is displayed when running `qiime --help` (like in @gregcaporaso's screenshot), and the long description is displayed when running `qiime <plugin-name> --help`. To test that it's working, I recommend submitting a PR to q2-feature-table to give the plugin a description, which should become visible from the command line. Let me know if you need some description text for that plugin.

Note: while working on the CLI, you'll need to run `qiime dev refresh-cache` to see your changes take effect. More details on that in the `note` towards the bottom of [this section](https://docs.qiime2.org/2017.2/plugins/developing/#initializing-a-plugin-package).

Does that all sound good to you?

**Comment by maxvonhippel** [comment]
@jairideout yeah absolutely, thanks!  I'll get on it.

**Comment by maxvonhippel** [comment]
This is my first time working with unit tests in Python, so it's certainly possible I may have messed something up.  That said, I ran all the unit tests in verbose on my machine in the virtual env with the plugins loaded per the instructions I got in the command line and it appears to be working:

````
....
. ok
test_description_text (qiime2.plugin.tests.test_plugin.TestPlugin) ... ok
test_methods (qiime2.plugin.tests.test_plugin.TestPlugin) ... ok
test_name (qiime2.plugin.tests.test_plugin.TestPlugin) ... ok
test_package (qiime2.plugin.tests.test_plugin.TestPlugin) ... ok
test_short_description_text (qiime2.plugin.tests.test_plugin.TestPlugin) ... ok
````

If I didn't mess anything up and this works, let me know and I'll get started on hooking up `q2cli` and any other cool integrations we can do.  I wonder if these values could also be used for automated documentation processes?  Could be cool to work that in, if you have something like that already in place.

I'll be off-and-on busy over the next week.  I have big exams Monday (math 401B) and Thursday (math 464).  But when I need a break from studying I can do some coding, so let me know what to fix or work on and I'll work on it when I can!

**Comment by jairideout** [comment]
Thanks @maxvonhippel! I just reviewed your PR (#222), it looks great. See my review there for specific comments.

Your tests are working just fine -- at the bottom of the page on your PR, you can see the status of the tests that are run by Travis-CI. Those tests are automatically run every time you commit and push to the branch you opened the PR from. If the status is green and says "All checks have passed", you're good to go! If tests are failing, click "Show all checks" and then "Details" next to the Travis-CI line. That'll show you the output from the tests that were run by Travis.

To see what Travis is running, check out [this section](https://github.com/qiime2/qiime2/blob/master/.travis.yml#L19-L21) of the .travis.yml file that's in the root of the repo. You can run those commands locally to confirm that the tests are passing.

>  I wonder if these values could also be used for automated documentation processes? Could be cool to work that in, if you have something like that already in place.

Funny you mentioned that -- the [QIIME 2 docs](https://github.com/qiime2/docs) repo has [a Sphinx extension](https://github.com/qiime2/docs/tree/master/source/sphinx_extensions/plugin_directory) that auto-generates plugin docs! You can see what the rendered docs look like [here](https://docs.qiime2.org/2017.2/plugins/available/). It'd be great to hook up these descriptions there too -- your call whether you want to work on q2cli first or the docs. For the docs, I'm thinking we'd want the "long" description in the section listing version, citation text, etc. (e.g. check out [this page](https://docs.qiime2.org/2017.2/plugins/available/diversity/)). For short description, it'd fit nicely in the title heading of that page (e.g. "diversity: short_description", or just "diversity" if there isn't a short description).

Let me know if you have any questions about these integrations and thanks again for working on all of this! No worries if you're busy with school and can't get to this stuff right away.

**Comment by maxvonhippel** [comment]
@jairideout awesome!  I love ReStructuredText - don't know it well enough yet, but I've been very impressed with it in my time using it on BASE9 (another project).  

I think I should probably work on q2cli first - that'll help me get a better handle on how all of the various parts of the code talk to each other and what the terminology ("module", "template", "visualizer", etc.) means.  Then I'll be in a more solid spot to give the docs a shot, since I'll actually understand what it is that I'm documenting.

**Comment by jairideout** [comment]
All sounds good, thanks @maxvonhippel!
